feat: FLS check, RFS and code refactoring
IBM/ansible-power-linux-sap pull request #68
Opened 2024-10-24 08:00 UTC by stafaniasaju

### Description

This PR includes following changes
- FLS Check
- Enabled RFS
- Code refactoring and revised nomenclature of
    1. powervs_prepare_rhel_sap and powervs_prepare_sles_sap -> powervs_os_registration and powervs_configure_os_for_sap
    2. powervs_client_enable_services and powervs_install_services -> configure-network-management-services
    3. powervs_storage_setup and powervs_swap_creation -> powervs_storage_and_swap_setup

2024-10-28 04:13 UTC, surajsbharadwaj requested changes
Changes requested

2024-10-28 04:13 UTC, surajsbharadwaj commented on roles/powervs_configure_os_for_sap/README.md
this readme needs update to describe about SLES and RHEL tuning. Also include description about RHEL inbuilt playbooks, giving reference links to RHEL SAP roles.

2024-10-28 04:13 UTC, surajsbharadwaj commented on roles/powervs_os_registration/README.md
Since this is a role now, need explanation of vars used and its description, type etc

2024-10-28 04:13 UTC, surajsbharadwaj commented on roles/powervs_os_registration/meta/main.yml
> +  description: Preparing RHEL OS for SAP installations
PowerVS OS registration

2024-10-28 04:13 UTC, surajsbharadwaj commented on roles/powervs_os_registration/tasks/main.yml
> +- name: OS registration for RHEL
Power Virtual Server Full Linux Subscription OS Registration

2024-10-28 14:51 UTC, stafaniasaju commented on playbooks/vars/sample-powervs-configure-os-for-sap.yml
> +# byol:
Change implemented

2024-10-29 10:07 UTC, surajsbharadwaj commented on roles/powervs_os_registration/README.md
>  ### Preparing Operating System for SAP installations for RHEL or SLES
This sentence is incorrect

2024-10-29 10:08 UTC, surajsbharadwaj requested changes
One last change.

Also for readmes can you please add input parameters in table format ? name: type:description. 3 columns for every role :) Thank you

2024-11-04 18:26 UTC, surajsbharadwaj requested changes
3 small changes 1: Task deletion ,correction of titles and correction of a sentence

2024-11-04 18:26 UTC, surajsbharadwaj commented on roles/configure_network_management_services/tasks/configure_network_services_host.yml
>      - name: Include task to create NFS filesystem
This task must be removed

2024-11-04 18:26 UTC, surajsbharadwaj commented on roles/configure_network_management_services/README.md
> +# 3. Edit parameters in the monitoring configuration file
Configure variables should be the title

2024-11-04 18:26 UTC, surajsbharadwaj commented on roles/powervs_configure_os_for_sap/README.md
> +# 3. Edit parameters in the monitoring configuration file
Title should be Configuration Variables

2024-11-04 18:26 UTC, surajsbharadwaj commented on roles/powervs_configure_os_for_sap/README.md
> +| sap_solution  | String  |sap_solution: "HANA"  | SAP Solution to be installed on Power Virtual Server |
also include, sap_solution: "NETWEAVER"

2024-11-04 18:26 UTC, surajsbharadwaj commented on roles/powervs_os_registration/README.md
> +To prpeare the OS for SAP system, execute the ansible playbook:
To register a PowerVS LPAR OS

2024-11-04 18:27 UTC, surajsbharadwaj requested changes
See comments below

2024-11-05 11:13 UTC, surajsbharadwaj requested changes
Linting issues and detect secrets

2024-11-05 20:33 UTC, surajsbharadwaj approved these changes

2024-11-06 08:42 UTC, merged